/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef center_CONSTANTS_H
#define center_CONSTANTS_H

#include "center_types.h"

namespace center {

class centerConstants {
 public:
  centerConstants();

};

extern const centerConstants g_center_constants;

} // namespace

#endif
