/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "center_constants.h"

namespace center {

const centerConstants g_center_constants;

centerConstants::centerConstants() {
}

} // namespace

